- name: Updating Homebrew
  homebrew:
    update_homebrew: true
  
- name: Installing Homebrew Packages
  homebrew:
    name: "{{ item }}"
    state: "absent"
  with_items: '{{ brew_packages }}'

- name: Installing Homebrew Cask Packages
  homebrew_cask:
    name: "{{ item }}"
    state: "absent"
  with_items: '{{ brew_cask_packages }}'
