- name: include homebrew package install playbook
  include: ansible-macos-homebrew-packages.yml

- name: install pathogen.vim plugin
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.vim/autoload
    - ~/.vim/bundle

- name: install pathogen.vim
  get_url:
      url: https://tpo.pe/pathogen.vim
      dest: ~/.vim/autoload/pathogen.vim

- name: clone color theme for vim
  git: >
      repo=https://github.com/morhetz/gruvbox.git
      dest=~/.vim/bundle/gruvbox

- name: copy vimrc file 
  copy:
    src: files/vimrc
    dest: "{{home_dir}}.vimrc"

- name: copy inputrc file 
  copy:
    src: files/inputrc
    dest: "{{home_dir}}.inputrc"

- stat: path="{{home_dir}}.bash_profile"
  register: bash_profile_exists

- name: copy bash_profile
  copy:
    src: files/bash_profile
    dest: "{{home_dir}}.bash_profile"
  when: bash_profile_exists.stat.exists == False

- name: disbale terminal session
  shell: touch "{{home_dir}}.bash_sessions_disable"

- name: copy git bash-completion file
  copy:
    src: files/git-completion.bash
    dest: "{{home_dir}}.git-completion.bash"

- name: Test for git-completion in bash_profile
  shell: cat "{{home_dir}}.bash_profile"
  register: git_completion

- name: update bash_profile
  shell: echo "source ~/.git-completion.bash" >> "{{home_dir}}.bash_profile"
  when: git_completion.stdout.find('git-completion.bash') == -1

